@host = http://localhost:3000/api/user

###

GET {{host}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIwMTk3ZTM3NS0xN2U3LTcyYTctYTliYy1iZGNiZjUwNjUxZGYiLCJhY2NvdW50IjoidGVzdDEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3NTIyNTI3ODcsImV4cCI6MTc1MjI1NjM4N30.bS9q5vouLf_ai04WWPPscD66w_xzRQNb1NbMF6CoEGQ
