export enum INVALID_MESSAGE {
  ACCOUNT_IS_REQUIRED = "ACCOUNT_IS_REQUIRED",
  PASSWORD_IS_REQUIRED = "PASSWORD_IS_REQUIRED",
  PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS = "PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS",
  USERNAME_IS_REQUIRED = "USERNAME_IS_REQUIRED",
}
